### ISSUE TITLE
OPAL spec, constrains on OPAL calls

### ISSUE THREAD

**Issue by andreiw** [open-power/skiboot#13]
opal-spec.txt should probably describe the expected machine state across an OPAL call a bit better, in that (from reading Linux kernel code and skiboot):
- r1 is preserved, r12 is scratch, r13-r31 preserved
- 64-bit HV real mode
- big-endian (this is already mentioned)
- external interrupts disabled

**Comment by ozbenh** [comment]
On Tue, 2015-05-12 at 01:20 -0700, Andrei Warkentin wrote:
> opal-spec.txt should probably describe the expected machine state
> across an OPAL call a bit better, in that (from reading Linux kernel
> code and skiboot):
> 
>       * r1 is preserved, r12 is scratch, r13-r31 preserved
>       * 64-bit HV real mode
>       * big-endian (this is already mentioned)
>       * external interrupts disabled

Good point.

Ben.

**Comment by stewart-ibm** [comment]
Thanks for suggestion, I've made an addition to opal-spec.txt mentioning these things. It's not great docs, but it's there for when we need to turn it into something better.
