### ISSUE TITLE
Packaging for gard

### ISSUE THREAD

**Issue by robers97** [open-power/skiboot#135]
I noticed that gard is not packaged with opal-utils and it found its way on to my cluster after a service engineer used the machine.  It is incredibly handy for a sanity check for servicing an OPAL machine.  Any discussion to include it with opal-utils?

**Comment by stewart-ibm** [comment]
What OS? I'm pretty sure we've been packaging `opal-gard` in opal-utils for a very long time, I'd be surprised if `opal-gard` wasn't there

**Comment by robers97** [comment]
Stewart - issue on my side.  The team I've been working with was installing their own executable ./gard wheres the opal-utils names it opal-gard.  Thank you.
