### ISSUE TITLE
[Witherspoon] Unable to Install Ubuntu 16.04.03 on the witherspoon system

### ISSUE THREAD

**Issue by swe12345** [open-power/skiboot#137]
While installing it is stuck at Guided partition at 80%.
Unable to access the system.
Only on powering off and powering on the system able to access the system.
Unable to Install Ubuntu 16.04.03

System Configuration:
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.10-132"
VERSION_ID="v1.99.10-132-gdd48d6e-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.10-132"
BUILD_ID="v1.99.10"
```

![image](https://user-images.githubusercontent.com/25239870/31482777-3f604db0-af47-11e7-956b-6a0f1c33dd9b.png)

**Comment by stewart-ibm** [comment]
Nothing on console at all? Did the BMC capture any error logs? e.g. are we checkstopped? Can you get into xmon at all?
