### ISSUE TITLE
missing manpages

### ISSUE THREAD

**Issue by ngothan** [open-power/skiboot#140]
4 executables still do not have manpages:
  /usr/sbin/getscom
  /usr/sbin/getsram
  /usr/sbin/pflash
  /usr/sbin/putscom

**Comment by stewart-ibm** [comment]
https://patchwork.ozlabs.org/patch/866228/ will fix this.

**Comment by stewart-ibm** [comment]
Merged as of b7546b534d95112e44d84c3b9d510b2711746534
