### ISSUE TITLE
cec_reboot bug?

### ISSUE THREAD

**Issue by hlandau** [open-power/skiboot#142]
At some locations `platform.cec_reboot` is called like this:

```
  if (platform.cec_reboot())
    platform.cec_reboot();
```

Is this supposed be:

```
  if (platform.cec_reboot)
    platform.cec_reboot();
```

Locations:
https://github.com/open-power/skiboot/blob/master/hw/ipmi/ipmi-attn.c#L70
https://github.com/open-power/skiboot/blob/master/hw/ipmi/ipmi-attn.c#L79

**Comment by mikey** [comment]
Nice find... thanks.
Posted fix here:
http://patchwork.ozlabs.org/patch/844981/
