### ISSUE TITLE
OS failed to starts after successful installation.

### ISSUE THREAD

**Issue by empsoul3019** [open-power/skiboot#153]
Hi;

We have successfully installed Ubuntu 16.04 i our Power9 server and it's running without problems. But on the other hand, we have also successfully installed RHEL 7.4 LE for Power9 on the same server but we're having issues starting the OS:

 Petitboot (v1.6.3-p9911320)                                    ──────────────────────────────────────────────────────────────────────────────
  [Disk: sdc2 / 02545631-ff7b-40e1-a8c4-1994654cc80e]
    Red Hat Enterprise Linux Server (0-rescue-75381ae3c51b41868f7d0c98d5816e85)
 *  Red Hat Enterprise Linux Server (3.10.0-693.el7.ppc64le) 7.4 (Maipo)

  System information
  System configuration
  System status log
  Language
  Rescan devices
  Retrieve config from URL
  Plugins (0)
  Exit to shell

 ──────────────────────────────────────────────────────────────────────────────
 Enter=accept, e=edit, n=new, x=exit, l=language, g=log, h=help
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
[ 1164.155630] kexec_core: Starting new kernel
[ 1185.083150759,5] OPAL: Switch to big-endian OS
[ 1186.403840625,5] OPAL: Switch to little-endian OS

Both installations were made using SAN disks (not insternal disk) Do we need to use any special boot argument to start RHEL on the server?

Thanks,

**Comment by stewart-ibm** [comment]
You need the alt architecture RHEL build (it has a much newer kernel). A 3.10 based kernel won't work on power9
