### ISSUE TITLE
[   93.278332057,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xd001002f

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/skiboot#189]
With latest skiboot getting this error.
```
[   93.278332057,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xd001002f
[   93.278346982,6] IPMI: dropping non severe PEL event
[   93.278577108,7] UART: IRQ functional !
```

**Comment by stewart-ibm** [comment]
I don't seem to be seeing this on current skiboot on P8 or P9, I think we had a fix or two come in over the past $time_period. Let's re-open if it's still seen anywhere.

**Comment by madscientist159** [comment]
https://github.com/open-power/op-build/issues/2816
