### ISSUE TITLE
IPMI error messages not informative

### ISSUE THREAD

**Issue by shenki** [open-power/skiboot#191]
On Romulus running a recent OpenBMC we see this at runtime:
```
[ 1530.190010977,7] IPMI: Got error response 0xff
[ 2202.214789915,7] IPMI: Got error response 0xff
[ 2877.245739191,7] IPMI: Got error response 0xff
[ 3545.266926281,7] IPMI: Got error response 0xff
[ 4217.297737657,7] IPMI: Got error response 0xff
[ 4889.372341057,7] IPMI: Got error response 0xff
[ 5561.419423831,7] IPMI: Got error response 0xff
[ 6232.469543272,7] IPMI: Got error response 0xff
[ 6905.506635973,7] IPMI: Got error response 0xff
[ 7577.024111771,7] IPMI: Got error response 0xff
[ 8249.060314971,7] IPMI: Got error response 0xff
```

It's hard to know what's going wrong, and if it's a problem that needs fixing, with this information. We should see what can be done to make the messages informative, so we can report a bug to OpenBMC.

**Comment by hegdevasant** [comment]
I have added failed cmd and netfn .. Hopefully that will give some clue which command failed.

See commit  : 
commit 7516e3827e5044442b9b79fa44fe118e101207c8
Author: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
Date:   Mon Feb 4 11:31:31 2019 +0530

    core/ipmi: Improve error message

-Vasant
