### ISSUE TITLE
P8: Failed to open PNOR flash controller

### ISSUE THREAD

**Issue by artemsen** [open-power/skiboot#197]
Commit https://github.com/open-power/skiboot/commit/a43e9a66aae9812f8790c4a9290989bb0774d2a6 breakes PNOR flash functionality.
As result, skiboot is unable to load kernel.

We use _raw_flash_ style access in terms of skiboot (P8, OpenBMC AST2400).

Boot log:
```
[  110.097168975,3] PLAT: Failed to open PNOR flash controller
[  110.456003047,2] NVRAM: Failed to load
[  110.456087263,2] NVRAM: Failed to load
[  110.456159975,2] NVRAM: Failed to load
[  110.457452084,2] NVRAM: Failed to load
[  110.457548751,2] NVRAM: Failed to load
[  110.458644679,5] SLW: HB-provided idle states property found
[  110.458773085,2] NVRAM: Failed to load
[  110.458873826,5] OCC: All Chip Rdy after 0 ms
[  110.476041181,2] NVRAM: Failed to load
[  110.476235058,4] FLASH: Can't load resource id:2. No system flash found
...
[  116.145115646,5] INIT: Waiting for kernel...
[  116.145170913,5] INIT: platform wait for kernel load failed
[  116.145243176,5] INIT: Assuming kernel at 0x20000000
[  116.145306484,3] INIT: ELF header not found. Assuming raw binary.
[  116.145988137,2] NVRAM: Failed to load
[  116.200562769,5] INIT: Starting kernel at 0x20000000, fdt at 0x3079abc8 169929 bytes
[  116.200850015,0] FATAL: Kernel is zeros, can't execute!
[  116.201023311,0] Assert fail: core/init.c:591:0
[  116.201193515,0] Aborting!
```

**Comment by amboar** [comment]
Yep, need to do more testing on p8 by the looks

**Comment by amboar** [comment]
I've reproduced this on a Palmetto. Digging now.

**Comment by amboar** [comment]
After a wasting a bunch of time not driving op-build properly I think I've at least resolved the immediate problem: http://patchwork.ozlabs.org/patch/985731/

Please respond with a Tested-by if it works for you @artemsen

As for what's caused the bit to become set and why no-one has cleaned it up, well, I'm not sure. Probably need to dig further there.

**Comment by artemsen** [comment]
The patch resolves this issue, thanks!

**Comment by artemsen** [comment]
@amboar, there is another problem with commit a43e9a6 - we can't write PNOR flash:
```
# gard -f /dev/mtd0 clear all
Clearing the entire gard partition...[   34.797245] mtd mtd0: opal_flash_async_op(op=2) failed (rc -6)
mtd_erase: IOCTL to kernel failed! Input/output error
Couldn't erase the gard partition. Bailing out
done
libflash parameter error
```
skiboot-v6.2-rc2

Function [fl_wren()](https://github.com/open-power/skiboot/blob/10497d05169fe6e05cecb762a35c63c164469819/libflash/libflash.c#L122) always return FLASH_ERR_WREN_TIMEOUT.

**Comment by amboar** [comment]
Okay. I'm on leave for a few days, but I'll have a poke around when I return.

**Comment by amboar** [comment]
On the surface it seems odd to finger a43e9a6 for fl_wren() failing. Was this identified by bisection?

**Comment by artemsen** [comment]
You are right, I tried skiboot 9a830ee06c66058b1421c017b25a65a22921e9f6 (pre- a43e9a66aae9812f8790c4a9290989bb0774d2a6), the gard utility doesn't report any errors but it corrupts pnor flash, so next boot failed:
```
1.03487|ECC error in PNOR flash in section offset 0x00031000
1.03841|System shutting down with error status 0x60F
1.04045|System shutting down with error status 0x90FF0001
```
Skiboot a43e9a66aae9812f8790c4a9290989bb0774d2a6 with cherry-picked 7194e92cc700bfcc6f12f5fc12da06ef936bd2b8 works more carefully and report an error.

I'm trying to find the last working version, but it seems like this functionality was broken a long time ago.

I will create a new issue as soon as I get the results.

**Comment by stewart-ibm** [comment]
Artem Senichev <notifications@github.com> writes:
> You are right, I tried skiboot 9a830ee06c66058b1421c017b25a65a22921e9f6 (pre- a43e9a66aae9812f8790c4a9290989bb0774d2a6), the gard utility doesn't report any errors but it corrupts pnor flash, so next boot failed:
> ```
> 1.03487|ECC error in PNOR flash in section offset 0x00031000
> 1.03841|System shutting down with error status 0x60F
> 1.04045|System shutting down with error status 0x90FF0001
> ```

https://github.com/open-power/skiboot/issues/200 may be relevant here,
as could e247710814227a7122915ff44474e0c8aa26fd3a.

-- 
Stewart Smith
OPAL Architect, IBM.
