### ISSUE TITLE
FSPCT: No centaur memory detected after cold reset

### ISSUE THREAD

**Issue by saqibkh** [open-power/skiboot#21]
No centaur memory was detected after doing a cold reset of the BMC:

System Info:
BMC ip address= 9.41.164.80  name=habcap10.aus.stglabs.ibm.com
## OS ip address=9.41.164.12 name=habcap10p1.aus.stglabs.ibm.com

Following is a list of commands that were executed and their outcome:

HOST OS: $ sudo /home/tyan/skiboot/external/xscom-utils/getscom -l
[sudo] password for tyan:
Chip ID  | Rev   | Chip type
---------|-------|--------
80000005 | DD2.0 | Centaur memory buffer
80000004 | DD2.0 | Centaur memory buffer
80000001 | DD2.0 | Centaur memory buffer
80000000 | DD2.0 | Centaur memory buffer
00000000 | DD2.0 | P8 (Venice) processor
# ipmitool -H habcap10 -I lanplus -U ${Userid} -P ${Password} mc cold reset

HOST OS: $ sudo /home/tyan/skiboot/external/xscom-utils/getscom -l
[sudo] password for tyan:
Chip ID  | Rev   | Chip type
---------|-------|--------
00000000 | DD2.0 | P8 (Venice) processor   <===========  No Centaur Memory

Also attached is an output obtained from the serial port, which shows that the BMC was unable to write/detect these memory.
![centaur_memory_error](https://cloud.githubusercontent.com/assets/11544614/11795978/5631899a-a27f-11e5-8e28-36e67515fe8e.PNG)

**Comment by ozbenh** [comment]
On Mon, 2015-12-14 at 14:27 -0800, saqibkh wrote:
> No centaur memory was detected after doing a cold reset of the BMC:
> System Info:
> BMC ip address= 94116480 name=habcap10ausstglabsibmcom
> OS ip address=94116412 name=habcap10p1ausstglabsibmcom
> Following is a list of commands that were executed and their outcome:
> HOST OS: $ sudo /home/tyan/skiboot/external/xscom-utils/getscom -l
> [sudo] password for tyan:

This isn't a skiboot problem. HostBoot didn't forward the information
about the Centaurs to us.

**Comment by gery-toulouse** [comment]
Should be closed as not updated for nearly 18 months. Please reopen if needed.
