### ISSUE TITLE
Support N25Qx256Ax NOR flash

### ISSUE THREAD

**Issue by anoo1** [open-power/skiboot#22]
Commit 71c2d6b72be7213914e2708c884b45fa74f525e6 added support for N25Q256Ax which is what IBM is using, but Foxconn is using N25Qx256Ax for their Barreleye systems. So need to add N25Qx256Ax to pflash.

**Comment by ozbenh** [comment]
On Fri, 2015-12-18 at 13:22 -0800, anoo1 wrote:
> Commit 71c2d6b added support for N25Q256Ax which is what IBM is
> using, but Foxconn is using N25Qx256Ax for their Barreleye systems.
> So need to add N25Qx256Ax to pflash.

Is there any difference ?

Cheers,
Ben.

**Comment by anoo1** [comment]
They don't appear to be different. Just need the name added to the pflash library because currently pflash returns "unsupported chip". Norm has verified that adding the new name flashes the chip successfully by adding this chip name to the local pflash copy of openbmc.

**Comment by ozbenh** [comment]
On Wed, 2015-12-23 at 07:04 -0800, anoo1 wrote:
> They don't appear to be different. Just need the name added to the
> pflash library because currently pflash returns "unsupported chip".
> Norm has verified that adding the new name flashes the chip
> successfully by adding this chip name to the local pflash copy of
> openbmc.

Wait, you mean that it has a different flash ID than the non-x variant
? Ok, in that case, we do need to add it. It's weird though, usually
they keep the IDs the same for minor differences (there are other
commands to query more details).

Cheers,
Ben.

**Comment by williamspatrick** [comment]
@stewart-ibm - Please merge if appropriate.

**Comment by williamspatrick** [comment]
Err... I guess this is an issue and not a pull request.  @stewart-ibm can you code this up quick and put it in?  Or has it already been taken care of?

**Comment by anoo1** [comment]
A barreleye that just arrived has a "Winbond W25Q256BV" chip, so this chip needs to be added as well.

{ 0xef4019, 0x02000000, FL_ERASE_ALL | FL_CAN_4B | FL_ERASE_64K|FL_ERASE_BULK,    "Winbond W25Q256BV"},

**Comment by stewart-ibm** [comment]
@anoo1 since you have access to such a system and can test, can you please post a patch to skiboot@lists.ozlabs.org ? Or, I can post one and you can test it :)

@williamspatrick - for N25Qx256Ax, do we know the details for them? Again, I don't have direct access to such a system, so will need someone to at least test.

**Comment by anoo1** [comment]
Patch sent with the changes for both chips, N25Qx256Ax and W25Q256BV.

**Comment by anoo1** [comment]
Per Stewart, this has been merged to master as of 539720ca9b1543a35411511a4154d3c9e5e4dc84.
