### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by ghost** [open-power/skiboot#225]
We have a couple of random python2 scripts in the tree. They need to be ported to python3 before end of year as Jan 1st 2020 is when Python 2.7 is EOL

**Comment by sharkcz** [comment]
A grep thru current sources shows
````
./external/fwts/merge-fwts-olog:1:#!/usr/bin/env python2
./external/fwts/generate-fwts-olog:1:#!/usr/bin/env python2
./external/xscom-utils/adu_scoms.py:1:#!/usr/bin/python
./doc/DtsLexer.py:1:#!/usr/bin/python
````
and it is all about `print` with a single exception. Should be straightforward to fix it.

**Comment by sharkcz** [comment]
proposed fix in https://patchwork.ozlabs.org/project/skiboot/patch/20200604085350.10663-1-dan@danny.cz/
