### ISSUE TITLE
Parallel build is broken

### ISSUE THREAD

**Issue by k0da** [open-power/skiboot#27]
When trying to build with multiple jobs, build will fail..

commit 9997117f30cdecec9248c23722da44c734a57e14 just workarounds in spec file, while the situation when developer will want to look into it is really rare. IMO dependencies just needs to be fixed

**Comment by k0da** [comment]
Fix is merged, closing

**Comment by stewart-ibm** [comment]
Thanks for checking back and closing the issue!
