### ISSUE TITLE
petitboot：When the language is Chinese, no Chinese is displayed in petitboot

### ISSUE THREAD

**Issue by nancy-sunny** [open-power/skiboot#283]
Petitboot：Language
When the language is Chinese, no Chinese is displayed in petitboot.
Excuse me, how to configure to display Chinese？
I found that there is no locale folder under /usr/share/, how do I generate a locale folder？
thank you.

**Comment by rarbab** [comment]
I see you originally asked [here](https://github.com/open-power/op-build/issues/5845), which is probably the right place. I'll answer there.
