### ISSUE TITLE
With latest skiboot code on a firenze system failed to boot during p8_i2c_init.

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/skiboot#41]
Not sure what is exactly the cause for this failure, But tried same skiboot lid one time it is worked and later on boot is aborting in skiboot code.
[   83.344371236,5] SkiBoot skiboot-5.3.2-191-g69a9337 starting...
[   83.344378129,5] initial console log level: memory 7, driver 5
[   83.344381077,6] CPU: P8 generation processor(max 8 threads/core)
[   83.344383798,7] CPU: Boot CPU PIR is 0x0870 PVR is 0x004b0201
[   83.344386757,7] CPU: Initial max PIR set to 0x1fff
[   83.345046793,5] OPAL table: 0x300b6e40 .. 0x300b7310, branch table: 0x30002000
[   83.345053589,7] Parsing HDAT...
[   83.345055592,5] SPIRA-S found.
[   83.345061239,6] Got PCIA !
[   83.345064476,6] CORE[0]: HW_PROC_ID=2 PROC_CHIP_ID=0 EC=0x21 OK
[   83.345068323,6] CORE[0]: PIR=48 RES=48 OK (8 threads)
[   83.345071816,6]     Cache: I=32 D=64/512/8192/0
[   83.345124160,6] CORE[1]: HW_PROC_ID=3 PROC_CHIP_ID=0 EC=0x21 OK
[   83.345127666,6] CORE[1]: PIR=96 RES=96 OK (8 threads)
[   83.345130847,6]     Cache: I=32 D=64/512/8192/0
[   83.345183008,6] CORE[2]: HW_PROC_ID=4 PROC_CHIP_ID=0 EC=0x21 OK
[   83.345186506,6] CORE[2]: PIR=104 RES=104 OK (8 threads)
[   83.345189800,6]     Cache: I=32 D=64/512/8192/0
[   83.345243971,6] CORE[3]: HW_PROC_ID=5 PROC_CHIP_ID=0 EC=0x21 OK
[   83.345247410,6] CORE[3]: PIR=112 RES=112 OK (8 threads)
[   83.345250727,6]     Cache: I=32 D=64/512/8192/0
[   83.345306459,6] CORE[4]: HW_PROC_ID=6 PROC_CHIP_ID=1 EC=0x21 OK
[   83.345309943,6] CORE[4]: PIR=160 RES=160 OK (8 threads)
[   83.345313210,6]     Cache: I=32 D=64/512/8192/0
[   83.345370978,6] CORE[5]: HW_PROC_ID=8 PROC_CHIP_ID=1 EC=0x21 OK
[   83.345374363,6] CORE[5]: PIR=176 RES=176 OK (8 threads)
[   83.345377532,6]     Cache: I=32 D=64/512/8192/0
[   83.345437230,6] CORE[6]: HW_PROC_ID=9 PROC_CHIP_ID=1 EC=0x21 OK
[   83.345440672,6] CORE[6]: PIR=224 RES=224 OK (8 threads)
[   83.345443952,6]     Cache: I=32 D=64/512/8192/0
[   83.345506142,6] CORE[7]: HW_PROC_ID=11 PROC_CHIP_ID=1 EC=0x21 OK
[   83.345509699,6] CORE[7]: PIR=240 RES=240 OK (8 threads)
[   83.345512998,6]     Cache: I=32 D=64/512/8192/0
[   83.345577243,6] CORE[8]: HW_PROC_ID=12 PROC_CHIP_ID=2 EC=0x21 OK
[   83.345580866,6] CORE[8]: PIR=2080 RES=2080 OK (8 threads)
[   83.345584245,6]     Cache: I=32 D=64/512/8192/0
[   83.345650462,6] CORE[9]: HW_PROC_ID=13 PROC_CHIP_ID=2 EC=0x21 OK
[   83.345653998,6] CORE[9]: PIR=2088 RES=2088 OK (8 threads)
[   83.345657241,6]     Cache: I=32 D=64/512/8192/0
[   83.345725430,6] CORE[10]: HW_PROC_ID=14 PROC_CHIP_ID=2 EC=0x21 OK
[   83.345728954,6] CORE[10]: PIR=2096 RES=2096 OK (8 threads)
[   83.345732321,6]     Cache: I=32 D=64/512/8192/0
[   83.345802194,6] CORE[11]: HW_PROC_ID=17 PROC_CHIP_ID=2 EC=0x21 OK
[   83.345805742,6] CORE[11]: PIR=2160 RES=2160 OK [boot] (8 threads)
[   83.345809567,6]     Cache: I=32 D=64/512/8192/0
[   83.345881043,6] CORE[12]: HW_PROC_ID=18 PROC_CHIP_ID=3 EC=0x21 OK
[   83.345884583,6] CORE[12]: PIR=2208 RES=2208 OK (8 threads)
[   83.345888000,6]     Cache: I=32 D=64/512/8192/0
[   83.345962527,6] CORE[13]: HW_PROC_ID=19 PROC_CHIP_ID=3 EC=0x21 OK
[   83.345966109,6] CORE[13]: PIR=2216 RES=2216 OK (8 threads)
[   83.345969454,6]     Cache: I=32 D=64/512/8192/0
[   83.346045787,6] CORE[14]: HW_PROC_ID=20 PROC_CHIP_ID=3 EC=0x21 OK
[   83.346049357,6] CORE[14]: PIR=2224 RES=2224 OK (8 threads)
[   83.346052787,6]     Cache: I=32 D=64/512/8192/0
[   83.346131208,6] CORE[15]: HW_PROC_ID=21 PROC_CHIP_ID=3 EC=0x21 OK
[   83.346134797,6] CORE[15]: PIR=2272 RES=2272 OK (8 threads)
[   83.346138123,6]     Cache: I=32 D=64/512/8192/0
[   83.346230153,6] IPLPARAMS: 1 serial ports in array
[   83.346233762,6] IPLPARAMS: Serial 0 rsrc: 2a00 loc: U78CB.001.WZS002B-P1-C1-T1
[   83.346246288,7] MS VPD: is at 0x31202ca0
[   83.346248727,7] MS VPD: MSAC is at 0x31202d10
[   83.346251619,7] MS VPD: TCMS is at 0x31202d2c
[   83.346254049,7] MS VPD: Maximum configured address: 0x8000002fffffffff
[   83.346257237,7] MS VPD: Maximum possible address: 0x8000002fffffffff
[   83.346260669,7] MS VPD: 0x31202ca0, area 0: installed functional shared
[   83.346477059,7]   Range: 0x0000002000000000..0x0000002800000000 on Chip 0x0 mattr: 0xa0000
[   83.346498710,7] MS VPD: 0x31202ca0, area 1: installed functional shared
[   83.346521324,7]   Range: 0x0000002000000000..0x0000002800000000 on Chip 0x0 mattr: 0xa0000
[   83.346534671,7] MS VPD: 0x31202ca0, area 2: installed functional shared
[   83.346558078,7]   Range: 0x0000000000000000..0x0000001000000000 on Chip 0x1 mattr: 0xa0000
[   83.346578809,7] MS VPD: 0x31202ca0, area 3: installed functional shared
[   83.346601842,7]   Range: 0x0000000000000000..0x0000001000000000 on Chip 0x1 mattr: 0xa0000
[   83.346614848,7] MS VPD: 0x31202ca0, area 4: installed functional shared
[   83.346638786,7]   Range: 0x0000002800000000..0x0000003000000000 on Chip 0x10 mattr: 0xa0000
[   83.346661199,7] MS VPD: 0x31202ca0, area 5: installed functional shared
[   83.346685304,7]   Range: 0x0000002800000000..0x0000003000000000 on Chip 0x10 mattr: 0xa0000
[   83.346699118,7] MS VPD: 0x31202ca0, area 6: installed functional shared
[   83.346724262,7]   Range: 0x0000001000000000..0x0000002000000000 on Chip 0x11 mattr: 0xa0000
[   83.346747071,7] MS VPD: 0x31202ca0, area 7: installed functional shared
[   83.346772342,7]   Range: 0x0000001000000000..0x0000002000000000 on Chip 0x11 mattr: 0xa0000
[   83.346785678,6] MS VPD: Total MB of RAM: 0x30000
[   83.346788992,6] XSCOM: Found HW ID 0x0 (PCID 0x0) @ 0x3fc0000000000
[   83.346817719,4] VPD: CCIN desc not available for : 54E5
[   83.346972196,6] XSCOM: Found HW ID 0x1 (PCID 0x1) @ 0x3fc0800000000
[   83.347001758,4] VPD: CCIN desc not available for : 54E5
[   83.347157033,6] XSCOM: Found HW ID 0x10 (PCID 0x2) @ 0x3fc8000000000
[   83.347186848,4] VPD: CCIN desc not available for : 54E5
[   83.347341075,6] XSCOM: Found HW ID 0x11 (PCID 0x3) @ 0x3fc8800000000
[   83.347371632,4] VPD: CCIN desc not available for : 54E5
[   83.347533416,6] FSP #0: FSP HW version 2, SW version 1, chip DD1.0
[   83.347540550,7] FSP #0: Found 2 IO PATH
[   83.347542932,7] FSP #0: IO PATH 0 is Active PSI Link, GXHB at 8003fffe80000000
[   83.347596919,7] FSP #0: IO PATH 1 is Backup PSI Link, GXHB at 8003fffe80100000
[   83.347678374,7] CHIPTOD: Found on chip 0x0 [primary]
[   83.347714015,7] CHIPTOD: Found on chip 0x1 
[   83.347750158,7] CHIPTOD: Found on chip 0x10 [secondary]
[   83.347788450,7] CHIPTOD: Found on chip 0x11 
[   83.347928522,6] CEC: HUB FRU 0 is CPU Card
[   83.347931393,6] CEC:   2 chips in FRU
[   83.347933658,7] CEC:   IO Hub Chip #0 OK
[   83.347935859,7] CEC:   PChip: 0 HUB ID: 0001 [EC=0x21] Hub#=0)
[   83.347939097,6] CEC:     Murano !
[   83.347941022,6] CEC:     HW CHIP=0x0, HW TOPO=0x0000
[   83.347976807,7] CEC:     ibm,loc-code: U78CB.001.WZS002B-P1-C32 (SLCA rsrc 0x1000)
[   83.347989730,7] CEC:     ibm,loc-code: U78CB.001.WZS002B-P1-C32 (SLCA rsrc 0x1000)
[   83.347997622,7] CEC:   IO Hub Chip #1 OK
[   83.347999764,7] CEC:   PChip: 1 HUB ID: 0001 [EC=0x21] Hub#=1)
[   83.348002952,6] CEC:     Murano !
[   83.348004947,6] CEC:     HW CHIP=0x1, HW TOPO=0x0010
[   83.348041820,7] CEC:     ibm,loc-code: U78CB.001.WZS002B-P1-C32 (SLCA rsrc 0x1000)
[   83.348054718,7] CEC:     ibm,loc-code: U78CB.001.WZS002B-P1-C32 (SLCA rsrc 0x1000)
[   83.348064398,7] CEC:     ibm,io-base-loc-code: U78CB.001.WZS002B-P1 (SLCA rsrc 0x800)
[   83.348072097,7] CEC:     LXRn=0 LXR=3100040100300042
[   83.348074969,7] CEC:     LX Info added to 30300010
[   83.348078084,6] CEC: HUB FRU 1 is CPU Card
[   83.348080786,6] CEC:   2 chips in FRU
[   83.348082942,7] CEC:   IO Hub Chip #0 OK
[   83.348085123,7] CEC:   PChip: 2 HUB ID: 0001 [EC=0x21] Hub#=2)
[   83.348088348,6] CEC:     Murano !
[   83.348090391,6] CEC:     HW CHIP=0x10, HW TOPO=0x0100
[   83.348130117,7] CEC:     ibm,loc-code: U78CB.001.WZS002B-P1-C33 (SLCA rsrc 0x1002)
[   83.348138142,7] CEC:   IO Hub Chip #1 OK
[   83.348140274,7] CEC:   PChip: 3 HUB ID: 0001 [EC=0x21] Hub#=3)
[   83.348143541,6] CEC:     Murano !
[   83.348145605,6] CEC:     HW CHIP=0x11, HW TOPO=0x0110
[   83.348187442,7] CEC:     ibm,loc-code: U78CB.001.WZS002B-P1-C33 (SLCA rsrc 0x1002)
[   83.348200122,7] CEC:     ibm,loc-code: U78CB.001.WZS002B-P1-C33 (SLCA rsrc 0x1002)
[   83.348209011,7] CEC:     ibm,io-base-loc-code: U78CB.001.WZS002B-P1 (SLCA rsrc 0x800)
[   83.348216700,7] CEC:     LXRn=0 LXR=3100040100300042
[   83.348219552,7] CEC:     LX Info added to 30300010
[   83.348264438,4] VPD: Model name 8284-22A not known
[   83.348302045,4] VPD: CCIN desc not available for : 2B08
[   83.348359473,7] HBRT: Found mini-DT at 0x0x3140aae8 size: 0x00001000
[   83.348431712,6] Parsing HDAT...done
[   83.348532276,5] XSCOM: chip 0x0 at 0x3fc0000000000 [P8E DD2.1]
[   83.348539101,5] XSCOM: chip 0x1 at 0x3fc0800000000 [P8E DD2.1]
[   83.348545622,5] XSCOM: chip 0x10 at 0x3fc8000000000 [P8E DD2.1]
[   83.348552081,5] XSCOM: chip 0x11 at 0x3fc8800000000 [P8E DD2.1]
[   83.348557942,6] XSTOP: ibm,sw-checkstop-fir prop not found
[   83.348560793,6] MFSI 0:0: Initialized
[   83.348563052,6] MFSI 0:2: Initialized
[   83.348565242,6] MFSI 0:1: Initialized
[   83.348567744,6] MFSI 1:0: Initialized
[   83.348569975,6] MFSI 1:2: Initialized
[   83.348572155,6] MFSI 1:1: Initialized
[   83.348574642,6] MFSI 10:0: Initialized
[   83.348576881,6] MFSI 10:2: Initialized
[   83.348579142,6] MFSI 10:1: Initialized
[   83.348581594,6] MFSI 11:0: Initialized
[   83.348583785,6] MFSI 11:2: Initialized
[   83.348585958,6] MFSI 11:1: Initialized
[   83.348845504,6] MEM: parsing reserved memory from reserved-names/-ranges properties
[   83.348851933,7] HOMER: Init chip 0
[   83.348855174,7]   PBA BAR0 : 0x0000000000000000
[   83.348857808,7]   PBA MASK0: 0x0000000000000000
[   83.348861224,7]   PBA BAR2 : 0x4000002ffda00000
[   83.348863964,7]   PBA MASK2: 0x0000000000000000
[   83.348866566,7]   SLW Image at 0x2ffda00000 size 1MB
[   83.348869740,4] SLW image is not reserved! Reserving
[   83.348874470,7]   PBA BAR3 : 0x0000000003b00000
[   83.348877143,7]   PBA MASK3: 0x0000000000000000
[   83.348879692,7]   OCC Common Area at 0x3b00000 size 1MB
[   83.348882530,7] HOMER: Init chip 1
[   83.348885406,7]   PBA BAR0 : 0x0000000000000000
[   83.348887908,7]   PBA MASK0: 0x0000000000000000
[   83.348891340,7]   PBA BAR2 : 0x4000002ffde00000
[   83.348894087,7]   PBA MASK2: 0x0000000000000000
[   83.348896708,7]   SLW Image at 0x2ffde00000 size 1MB
[   83.348899539,4] SLW image is not reserved! Reserving
[   83.348904342,7]   PBA BAR3 : 0x0000000000000000
[   83.348906933,7]   PBA MASK3: 0x0000000000000000
[   83.348909628,7] HOMER: Init chip 16
[   83.348912512,7]   PBA BAR0 : 0x0000000000000000
[   83.348914980,7]   PBA MASK0: 0x0000000000000000
[   83.348918391,7]   PBA BAR2 : 0x4000002ffe200000
[   83.348921092,7]   PBA MASK2: 0x0000000000000000
[   83.348923687,7]   SLW Image at 0x2ffe200000 size 1MB
[   83.348926517,4] SLW image is not reserved! Reserving
[   83.348931357,7]   PBA BAR3 : 0x0000000000000000
[   83.348933918,7]   PBA MASK3: 0x0000000000000000
[   83.348936493,7] HOMER: Init chip 17
[   83.348939394,7]   PBA BAR0 : 0x0000000000000000
[   83.348941890,7]   PBA MASK0: 0x0000000000000000
[   83.348945287,7]   PBA BAR2 : 0x4000002ffe600000
[   83.348947940,7]   PBA MASK2: 0x0000000000000000
[   83.348950441,7]   SLW Image at 0x2ffe600000 size 1MB
[   83.348953348,4] SLW image is not reserved! Reserving
[   83.348958239,7]   PBA BAR3 : 0x0000000000000000
[   83.348960778,7]   PBA MASK3: 0x0000000000000000
[   83.358874291,7] HBRT: Chip 0 HOMER base 0000002001400000 : 00400000
[   83.358879889,7] HBRT: OCC common base 0000002000800000 : 00800000
[   83.364026696,7] HBRT: Chip 1 HOMER base 000000003a000000 : 00400000
[   83.364038909,7] HBRT: OCC common base 0000002000800000 : 00800000
[   83.369990270,7] HBRT: Chip 16 HOMER base 0000002800400000 : 00400000
[   83.370001552,7] HBRT: OCC common base 0000002000800000 : 00800000
[   83.375962319,7] HBRT: Chip 17 HOMER base 0000001000400000 : 00400000
[   83.375970429,7] HBRT: OCC common base 0000002000800000 : 00800000
[   83.375989846,7] CPU idle state device tree init
[   83.375996870,4] SLW: HB-provided idle states property found
[   83.376185592,5] PLAT: Detected Firenze platform
[   83.376192111,6] CPU: CPU from DT PIR=0x0030 Server#=0x30 State=3
[   83.376201415,6] CPU:  8 secondary threads
[   83.376205496,6] CPU: CPU from DT PIR=0x0060 Server#=0x60 State=3
[   83.376213745,6] CPU:  8 secondary threads
[   83.376217815,6] CPU: CPU from DT PIR=0x0068 Server#=0x68 State=3
[   83.376225988,6] CPU:  8 secondary threads
[   83.376230180,6] CPU: CPU from DT PIR=0x0070 Server#=0x70 State=3
[   83.376238411,6] CPU:  8 secondary threads
[   83.376242475,6] CPU: CPU from DT PIR=0x00a0 Server#=0xa0 State=3
[   83.376250722,6] CPU:  8 secondary threads
[   83.376254739,6] CPU: CPU from DT PIR=0x00b0 Server#=0xb0 State=3
[   83.376262879,6] CPU:  8 secondary threads
[   83.376266859,6] CPU: CPU from DT PIR=0x00e0 Server#=0xe0 State=3
[   83.376275011,6] CPU:  8 secondary threads
[   83.376279131,6] CPU: CPU from DT PIR=0x00f0 Server#=0xf0 State=3
[   83.376287237,6] CPU:  8 secondary threads
[   83.376291289,6] CPU: CPU from DT PIR=0x0820 Server#=0x820 State=3
[   83.376299877,6] CPU:  8 secondary threads
[   83.376303958,6] CPU: CPU from DT PIR=0x0828 Server#=0x828 State=3
[   83.376312285,6] CPU:  8 secondary threads
[   83.376316295,6] CPU: CPU from DT PIR=0x0830 Server#=0x830 State=3
[   83.376324667,6] CPU:  8 secondary threads
[   83.376328832,6] CPU: CPU from DT PIR=0x0870 Server#=0x870 State=3
[   83.376336891,6] CPU:  8 secondary threads
[   83.376341023,6] CPU: CPU from DT PIR=0x08a0 Server#=0x8a0 State=3
[   83.376349346,6] CPU:  8 secondary threads
[   83.376353401,6] CPU: CPU from DT PIR=0x08a8 Server#=0x8a8 State=3
[   83.376361677,6] CPU:  8 secondary threads
[   83.376365683,6] CPU: CPU from DT PIR=0x08b0 Server#=0x8b0 State=3
[   83.376373894,6] CPU:  8 secondary threads
[   83.376378004,6] CPU: CPU from DT PIR=0x08e0 Server#=0x8e0 State=3
[   83.376386377,6] CPU:  8 secondary threads
[   83.376392710,7] CPU: New max PIR set to 0x8e7
[   83.386559240,7] IRQ: Registering 0010..0015 ops @0x3008eea0 (data 0x30360740)
[   83.386579817,5] PSI[0x000]: Found PSI bridge [active=1]
[   83.386586952,5] PSI[0x001]: Working chip not found
[   83.386596327,7] IRQ: Registering 20010..20015 ops @0x3008eea0 (data 0x30360ad8)
[   83.386609822,5] PSI[0x010]: Found PSI bridge [active=0]
[   83.386617011,5] PSI[0x011]: Working chip not found
[   83.386620300,6] CPU: Setting up secondary CPU state
[   83.386623190,6] CPU: Calling in all processors...
[   83.386626057,7] INIT: CPU PIR 0x0871 called in
[   83.386626314,7] INIT: CPU PIR 0x0876 called in
[   83.386626229,7] INIT: CPU PIR 0x0877 called in
[   83.392892226,7] INIT: CPU PIR 0x0074 called in
[   83.392892221,7] INIT: CPU PIR 0x0071 called in
[   83.392892227,7] INIT: CPU PIR 0x0072 called in
[   83.385250535,7] INIT: CPU PIR 0x0037 called in
[   83.385250450,7] INIT: CPU PIR 0x0034 called in
[   83.392892228,7] INIT: CPU PIR 0x0076 called in
[   83.398216522,7] INIT: CPU PIR 0x00f1 called in
[   83.391118910,7] INIT: CPU PIR 0x006c called in
[   83.387647328,7] INIT: CPU PIR 0x08a5 called in
[   83.387647328,7] INIT: CPU PIR 0x08a2 called in
[   83.387647329,7] INIT: CPU PIR 0x08a7 called in
[   83.391269512,7] INIT: CPU PIR 0x00e5 called in
[   83.398216010,7] INIT: CPU PIR 0x00f6 called in
[   83.387647323,7] INIT: CPU PIR 0x08a0 called in
[   83.394239529,7] INIT: CPU PIR 0x08ae called in
[   83.396606711,7] INIT: CPU PIR 0x0836 called in
[   83.385250527,7] INIT: CPU PIR 0x0035 called in
[   83.399901020,7] INIT: CPU PIR 0x00a3 called in
[   83.392892230,7] INIT: CPU PIR 0x0073 called in
[   83.400881818,7] INIT: CPU PIR 0x08b5 called in
[   83.400881808,7] INIT: CPU PIR 0x08b0 called in
[   83.400637749,7] INIT: CPU PIR 0x0063 called in
[   83.400637031,7] INIT: CPU PIR 0x0065 called in
[   83.385250896,7] INIT: CPU PIR 0x0031 called in
[   83.392892527,7] INIT: CPU PIR 0x0075 called in
[   83.394239359,7] INIT: CPU PIR 0x08af called in
[   83.391269510,7] INIT: CPU PIR 0x00e7 called in
[   83.391269507,7] INIT: CPU PIR 0x00e3 called in
[   83.390072994,7] INIT: CPU PIR 0x00b6 called in
[   83.391118767,7] INIT: CPU PIR 0x006b called in
[   83.389746515,7] INIT: CPU PIR 0x0828 called in
[   83.389746520,7] INIT: CPU PIR 0x0829 called in
[   83.396607527,7] INIT: CPU PIR 0x0830 called in
[   83.400637436,7] INIT: CPU PIR 0x0066 called in
[   83.400637138,7] INIT: CPU PIR 0x0060 called in
[   83.388362617,7] INIT: CPU PIR 0x0823 called in
[   83.400637444,7] INIT: CPU PIR 0x0062 called in
[   83.398216741,7] INIT: CPU PIR 0x00f5 called in
[   83.399901017,7] INIT: CPU PIR 0x00a7 called in
[   83.390636904,7] INIT: CPU PIR 0x08e7 called in
[   83.390636903,7] INIT: CPU PIR 0x08e6 called in
[   83.390636975,7] INIT: CPU PIR 0x08e4 called in
[   83.387647331,7] INIT: CPU PIR 0x08a1 called in
[   83.394239196,7] INIT: CPU PIR 0x08aa called in
[   83.387647331,7] INIT: CPU PIR 0x08a4 called in
[   83.400881809,7] INIT: CPU PIR 0x08b4 called in
[   83.392893400,7] INIT: CPU PIR 0x0077 called in
[   83.388362396,7] INIT: CPU PIR 0x0821 called in
[   83.396606712,7] INIT: CPU PIR 0x0834 called in
[   83.392892225,7] INIT: CPU PIR 0x0070 called in
[   83.385250517,7] INIT: CPU PIR 0x0030 called in
[   83.385250626,7] INIT: CPU PIR 0x0032 called in
[   83.386626071,7] INIT: CPU PIR 0x0874 called in
[   83.400881827,7] INIT: CPU PIR 0x08b2 called in
[   83.400881814,7] INIT: CPU PIR 0x08b1 called in
[   83.385250541,7] INIT: CPU PIR 0x0036 called in
[   83.390072938,7] INIT: CPU PIR 0x00b1 called in
[   83.385250876,7] INIT: CPU PIR 0x0033 called in
[   83.398216012,7] INIT: CPU PIR 0x00f3 called in
[   83.399901249,7] INIT: CPU PIR 0x00a1 called in
[   83.391269508,7] INIT: CPU PIR 0x00e4 called in
[   83.398216015,7] INIT: CPU PIR 0x00f2 called in
[   83.400637446,7] INIT: CPU PIR 0x0067 called in
[   83.390073148,7] INIT: CPU PIR 0x00b4 called in
[   83.390072926,7] INIT: CPU PIR 0x00b0 called in
[   83.389746519,7] INIT: CPU PIR 0x082b called in
[   83.388362397,7] INIT: CPU PIR 0x0820 called in
[   83.388362908,7] INIT: CPU PIR 0x0825 called in
[   83.387647327,7] INIT: CPU PIR 0x08a3 called in
[   83.387647330,7] INIT: CPU PIR 0x08a6 called in
[   83.391269511,7] INIT: CPU PIR 0x00e6 called in
[   83.391269509,7] INIT: CPU PIR 0x00e2 called in
[   83.396606722,7] INIT: CPU PIR 0x0837 called in
[   83.399901019,7] INIT: CPU PIR 0x00a0 called in
[   83.386626072,7] INIT: CPU PIR 0x0873 called in
[   83.386626063,7] INIT: CPU PIR 0x0872 called in
[   83.400637443,7] INIT: CPU PIR 0x0061 called in
[   83.390636901,7] INIT: CPU PIR 0x08e5 called in
[   83.399901013,7] INIT: CPU PIR 0x00a6 called in
[   83.391269510,7] INIT: CPU PIR 0x00e0 called in
[   83.388362438,7] INIT: CPU PIR 0x0827 called in
[   83.388363136,7] INIT: CPU PIR 0x0822 called in
[   83.394239192,7] INIT: CPU PIR 0x08a8 called in
[   83.396607476,7] INIT: CPU PIR 0x0832 called in
[   83.390072928,7] INIT: CPU PIR 0x00b2 called in
[   83.390072931,7] INIT: CPU PIR 0x00b5 called in
[   83.398216011,7] INIT: CPU PIR 0x00f0 called in
[   83.399901745,7] INIT: CPU PIR 0x00a5 called in
[   83.394239192,7] INIT: CPU PIR 0x08ac called in
[   83.391119844,7] INIT: CPU PIR 0x006f called in
[   83.391269714,7] INIT: CPU PIR 0x00e1 called in
[   83.399901016,7] INIT: CPU PIR 0x00a4 called in
[   83.396606716,7] INIT: CPU PIR 0x0833 called in
[   83.396607949,7] INIT: CPU PIR 0x0835 called in
[   83.390072943,7] INIT: CPU PIR 0x00b7 called in
[   83.391118747,7] INIT: CPU PIR 0x006a called in
[   83.390636905,7] INIT: CPU PIR 0x08e1 called in
[   83.394239373,7] INIT: CPU PIR 0x08a9 called in
[   83.394239189,7] INIT: CPU PIR 0x08ad called in
[   83.394239352,7] INIT: CPU PIR 0x08ab called in
[   83.400881812,7] INIT: CPU PIR 0x08b3 called in
[   83.386626321,7] INIT: CPU PIR 0x0875 called in
[   83.390636906,7] INIT: CPU PIR 0x08e0 called in
[   83.400881833,7] INIT: CPU PIR 0x08b7 called in
[   83.400637466,7] INIT: CPU PIR 0x0064 called in
[   83.400881813,7] INIT: CPU PIR 0x08b6 called in
[   83.389746517,7] INIT: CPU PIR 0x082c called in
[   83.389746521,7] INIT: CPU PIR 0x082a called in
[   83.398216013,7] INIT: CPU PIR 0x00f7 called in
[   83.390636985,7] INIT: CPU PIR 0x08e3 called in
[   83.398216010,7] INIT: CPU PIR 0x00f4 called in
[   83.399901018,7] INIT: CPU PIR 0x00a2 called in
[   83.390636978,7] INIT: CPU PIR 0x08e2 called in
[   83.391118762,7] INIT: CPU PIR 0x0068 called in
[   83.391118735,7] INIT: CPU PIR 0x0069 called in
[   83.391118754,7] INIT: CPU PIR 0x006d called in
[   83.389746522,7] INIT: CPU PIR 0x082e called in
[   83.388362395,7] INIT: CPU PIR 0x0824 called in
[   83.396608253,7] INIT: CPU PIR 0x0831 called in
[   83.388362439,7] INIT: CPU PIR 0x0826 called in
[   83.389746518,7] INIT: CPU PIR 0x082d called in
[   83.389746520,7] INIT: CPU PIR 0x082f called in
[   83.390072942,7] INIT: CPU PIR 0x00b3 called in
[   83.391118741,7] INIT: CPU PIR 0x006e called in
[   83.389916655,5] CPU: All 128 processors called in...
[   83.389920823,6] CPU: enabling power management
[   83.389948335,6] CHIPTOD: Calculated MCBS is 0x4d (Cfreq=4157000000 Tfreq=32000000)
[   83.389950137,7] CHIPTOD: Base TFMR=0x4d12000000000000
[   83.388574402,7] CHIPTOD: Master sync on CPU PIR 0x0030...
[   83.444933551,7] CHIPTOD: Slave sync on CPU PIR 0x0060...
[   83.476384424,7] CHIPTOD: Slave sync on CPU PIR 0x0068...
[   84.7127758,7] CHIPTOD: Slave sync on CPU PIR 0x0070...
[   84.55105771,7] CHIPTOD: Slave sync on CPU PIR 0x00a0...
[   84.86246833,7] CHIPTOD: Slave sync on CPU PIR 0x00b0...
[   84.128413477,7] CHIPTOD: Slave sync on CPU PIR 0x00e0...
[   84.176329644,7] CHIPTOD: Slave sync on CPU PIR 0x00f0...
[   84.207477558,7] CHIPTOD: Slave sync on CPU PIR 0x0820...
[   84.249830712,7] CHIPTOD: Slave sync on CPU PIR 0x0828...
[   84.297658213,7] CHIPTOD: Slave sync on CPU PIR 0x0830...
[   84.328648090,7] CHIPTOD: Slave sync on CPU PIR 0x0870...
[   84.365760435,7] CHIPTOD: Slave sync on CPU PIR 0x08a0...
[   84.413592283,7] CHIPTOD: Slave sync on CPU PIR 0x08a8...
[   84.461473388,7] CHIPTOD: Slave sync on CPU PIR 0x08b0...
[   84.492467875,7] CHIPTOD: Slave sync on CPU PIR 0x08e0...
[    1.135475609,7] CHIPTOD: PIR 0x0030 TB=2697b190
[    1.140597493,7] CHIPTOD: PIR 0x0060 TB=26e5d8ec
[    1.145718830,7] CHIPTOD: PIR 0x0068 TB=2733fe25
[    1.150840107,7] CHIPTOD: PIR 0x0070 TB=27822322
[    1.155962292,7] CHIPTOD: PIR 0x00a0 TB=27d04bab
[    1.161083636,7] CHIPTOD: PIR 0x00b0 TB=281e70ec
[    1.166205599,7] CHIPTOD: PIR 0x00e0 TB=286c9896
[    1.171327053,7] CHIPTOD: PIR 0x00f0 TB=28babe43
[    1.176477805,7] CHIPTOD: PIR 0x0820 TB=29095663
[    1.181598874,7] CHIPTOD: PIR 0x0828 TB=29577a91
[    1.186720072,7] CHIPTOD: PIR 0x0830 TB=29a59f3d
[    1.191841664,7] CHIPTOD: PIR 0x0870 TB=29f3c576
[    1.191845273,7] CHIPTOD: PIR 0x08a0 TB=29f3d390
[    1.196966356,7] CHIPTOD: PIR 0x08a8 TB=2a41f7cb
[    1.202087738,7] CHIPTOD: PIR 0x08b0 TB=2a901d30
[    1.207209751,7] CHIPTOD: PIR 0x08e0 TB=2ade450e
[    1.212343017,7] CHIPTOD: TOD Topology in Use: Primary
[    1.212344512,7] CHIPTOD:   Primary configuration:
[    1.212345636,7] CHIPTOD:   Chip id: 0, Role: MDMT, Status: Active Master
[    1.212347195,7] CHIPTOD:   Secondary configuration:
[    1.212348252,7] CHIPTOD:   Chip id: 16, Role: MDMT, Status: Backup Master
[    1.212366090,3] DT: Unexpected property length /xscom@3fc0000000000/i2cm@a0020/clock-frequency
[    1.212369108,3] DT: Expected len: 4 got len: 8
[    1.212370117,0] Assert fail: core/device.c:603:0
[    1.212371550,0] Aborting!
CPU 0870 Backtrace:
 S: 0000000033dc39e0 R: 0000000030013758   .backtrace+0x24
 S: 0000000033dc3a60 R: 0000000030018e0c   ._abort+0x4c
 S: 0000000033dc3ae0 R: 0000000030018e88   .assert_fail+0x34
 S: 0000000033dc3b60 R: 0000000030023da4   .dt_require_property+0xb4
 S: 0000000033dc3bf0 R: 000000003002403c   .dt_prop_get_u32+0x14
 S: 0000000033dc3c60 R: 000000003004e884   .p8_i2c_init+0x12c
 S: 0000000033dc3e30 R: 0000000030014684   .main_cpu_entry+0x4a8
 S: 0000000033dc3f00 R: 00000000300025a0   boot_entry+0x198

**Comment by stewart-ibm** [comment]
What FSP firmware version?

**Comment by pridhiviraj** [comment]
system is in latest FW860.10 (TV860_047) driver b0922a_1640.861

**Comment by stewart-ibm** [comment]
@hegdevasant has an idea and should post a patch shortly.

**Comment by pridhiviraj** [comment]
cool, thanks

**Comment by hegdevasant** [comment]
Please test with https://patchwork.ozlabs.org/patch/675988/

I've tested on my box and its working fine.

-Vasant

**Comment by pridhiviraj** [comment]
Hi vasant
Tested the patch, system booted fine to petitboot without any abort in skiboot phase.
Thanks

**Comment by stewart-ibm** [comment]
and merged. Thanks!
