### ISSUE TITLE
hw/phb3: failure in phb3_init_hw() doesn't cause phb3_creset() to abort

### ISSUE THREAD

**Issue by ajdlinux** [open-power/skiboot#43]
`phb3_init_hw()` can fail for a variety of reasons, including DLP reset timeout, root complex config space init failure, etc.

If phb3_init_hw() is being invoked as part of a creset, phb3_creset() valiantly tries to ignore the failure and soldier on into doing an freset. Presumably the right thing to do is to check the return value and abort.

**Comment by ajdlinux** [comment]
Patch: http://patchwork.ozlabs.org/patch/684906/

**Comment by gery-toulouse** [comment]
Should be closed as not updated for nearly 18 months. Please reopen if needed.
