### ISSUE TITLE
pflash fails to read Macronix chips when using slow timings

### ISSUE THREAD

**Issue by cyrilbur-ibm** [open-power/skiboot#46]
In the rare event that flash chip is fully erased before pflash initialises, pflash will use conservative settings and timings.
For Macronix chips it appears these settings/timings permit correct writes but slightly corrupt reads which prevents pflash from verifying its writes causing aborts and rendering chips unwritable.

A fix is being refined.

This bug has existed since the very beginning of pflash.

**Comment by gery-toulouse** [comment]
Should be closed as not commented for 2 years. Please retest with a recent version and reopen if needed
