### ISSUE TITLE
OPAL Console issue on fsp platforms.

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/skiboot#55]
Below test steps causes the console messages are not coming on fsp ipmi console.
1. Connect ipmi sol console
2. Power OFF/ON the system
3. IPL messages will be coming to ipmi console
4. Trigger system dump from FSP
5. Wait for system dump to finish & immediately IPL starts automatically.
6. System IPL happening & boots to host OS, but all this IPL messages are not coming into active ipmi
console which was activated at the start of test.
Issue is coming with latest skiboot code.

**Comment by sammj** [comment]
Do you see any output over IPMI (eg, Petitboot, host OS login prompt), or nothing at all?

Please post kernel and skiboot logs, either from Petitboot or the host OS depending on if you have Petitboot output or not.

**Comment by williamspatrick** [comment]
Are you sure that the FSP's `ipmi sol` is intended for this use?  Does the content come over the normal virtual TTY protocol just fine and just not over `ipmi sol`?  If it is only a problem with SOL it is likely a problem with the FSP and not with skiboot (or any other open-source firmware).

**Comment by pridhiviraj** [comment]
@sammj yes, nothing over ipmi console, But system boots fine, In order to access the system, we need to deactivate existing console and connect again.
Okay, will attach the required logs
Thanks

**Comment by pridhiviraj** [comment]
[opal_msg_log_55.txt](https://github.com/open-power/skiboot/files/710093/opal_msg_log_55.txt)

**Comment by pridhiviraj** [comment]
[kernel_log_55.txt](https://github.com/open-power/skiboot/files/710094/kernel_log_55.txt)

**Comment by pridhiviraj** [comment]
@williamspatrick 
i know skiboot output won,t come on FSP's ipmi sol console, But even petitboot kernel and host kernel boot messages are also not coming into ipmi sol console

**Comment by williamspatrick** [comment]
I'm surprised that anything comes over the ipmi console.

Just to be clear, are you suggesting you see the kernel messages sometimes but not always on the ipmi console?

@tomjoseph83 - Is this something you are aware of the behavior from an FSP perspective?

**Comment by pridhiviraj** [comment]
@williamspatrick 
To be clear i am not seeing any IPL or kernel messages all the times in-case of a system dump followed by immediate IPL. In all remaining situations Host firmware able to use FSP ipmi sol console except in the above case.

**Comment by tomjoseph83** [comment]
@pridhiviraj 

I think i first step we can do to isolate the problem, is to see whether the console data is available on the vtty session.

Secondly was the IPMI SOL session was active throughout and did it disconnect.

**Comment by pridhiviraj** [comment]
@tomjoseph83 
yes, ipmi sol session is active throughout.
How can i check whether the data is available on the vtty session?

Thanks

**Comment by sammj** [comment]
> I'm surprised that anything comes over the ipmi console.

Unless we're talking about different things here, we should definitely be seeing output from the Petitboot kernel over IPMI. On FSP systems this is the primary interface to Petitboot.

**Comment by williamspatrick** [comment]
I assumed, perhaps incorrectly, that the Vtty is the primary path like it is for PowerVM.

**Comment by pridhiviraj** [comment]
This issue is not reproducible if i try manually. the testcase automated here https://github.com/open-power/op-test-framework/pull/99/commits/f0d56376410c01d8c6d1915b3f6da5a9ac0af436 which is able to reproduce. To reproduce this issue we need to run this automated system dump testcase & connect ipmi sol console in parallel in a different terminal when test starts. And i am going to raise an internal bugzilla to track this issue as i am able reproduce with official firmware release build also. So closing the issue here.

**Comment by pridhiviraj** [comment]
Raised an internal BugZilla ID 150765

**Comment by ozbenh** [comment]
On Tue, 2017-01-17 at 07:26 -0800, Paidipeddi Pridhiviraj wrote:
> @tomjoseph83
> yes, ipmi sol session is active throughout.
> How can i check whether the data is available on the vtty session?
> Thanks

Also check in the OPAL log if you see VTY disconnection messages from
the FSP...

Cheers,
Ben.
