### ISSUE TITLE
OPAL: Nvram query for pcie-max-link-speed failed with bad format for every reboot.

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/skiboot#71]
cat /sys/firmware/opal/msglog | grep -i nvram  
[    6.414070525,5] FSP: NVRAM file size from FSP is 1048576 bytes
[    6.414071859,5] NVRAM: Size is 1024 KB
[    6.414074602,5] FSP NVRAM: Opening nvram...
[    6.414653835,3] NVRAM: Partition at offset 0x0 has incorrect 0 length
[    6.414655209,3] NVRAM: Look up for 'pcie-max-link-speed' failed due to bad format!
[   21.115604444,6] NVRAM: Layout appears sane
[   21.126212154,7] NVRAM: 'bootargs' not found

After upgrading skiboot to latest, seeing for every reboot nvram_validate failed with bad format while we are looking for 'pcie-max-link-speed' 
I didn't set any link speed using nvram tool.

[   42.392268691,5] SkiBoot bd87856 starting...

**Comment by oohal** [comment]
I think this was fixed in 92813a8bf9.
