### ISSUE TITLE
System fails to boot when flashing upstream skiboot with upstream pflash.

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/skiboot#86]
[SOL Session operational.  Use ~? for help]
  3.15308|Ignoring boot flags, incorrect version 0x0
  3.22230|ISTEP  6. 3
  3.58154|ISTEP  6. 4
  3.58218|ISTEP  6. 5
  8.33802|HWAS|PRESENT> DIMM[03]=AAAA0000AAAA0000
  8.33802|HWAS|PRESENT> Membuf[04]=CC00000000000000
  8.33803|HWAS|PRESENT> Proc[05]=8000000000000000
  8.47936|ISTEP  6. 6
  8.62452|ISTEP  6. 7
 10.44392|ISTEP  6. 8
 10.49070|ISTEP  6. 9
 11.49723|ISTEP  6.10
 11.49789|ISTEP  6.11
 11.61672|ISTEP  6.12
 11.62665|ISTEP  6.13
 11.62808|ISTEP  7. 1
 11.72621|ISTEP  7. 2
 11.83033|ISTEP  7. 3
 11.85071|ISTEP  7. 4
 11.88902|ISTEP  7. 5
 12.08204|ISTEP  7. 6
 12.12044|ISTEP  7. 7
 12.13041|ISTEP  7. 8
 12.20252|ISTEP  7. 9
 12.20303|ISTEP  8. 1
 12.31792|ISTEP  8. 2
 12.31868|ISTEP  8. 3
 12.32840|ISTEP  8. 4
 12.32899|ISTEP  8. 5
 12.35455|ISTEP  8. 6
 12.96469|ISTEP  8. 7
 12.96583|ISTEP  8. 8
 13.00342|ISTEP  9. 1
 13.34028|ISTEP  9. 2
 13.81218|ISTEP 10. 1
 14.03869|ISTEP 10. 2
 14.93036|ISTEP 10. 3
 14.93103|ISTEP 10. 4
 14.93190|ISTEP 10. 5
 14.93237|ISTEP 10. 6
 14.95623|ISTEP 10. 7
 14.95719|ISTEP 10. 8
 14.95767|ISTEP 10. 9
 15.02841|ISTEP 10.10
 15.02940|ISTEP 10.11
 15.03040|ISTEP 10.12
 15.12324|ISTEP 10.13
 15.12424|ISTEP 10.14
 15.12524|ISTEP 11. 1
 15.30373|ISTEP 11. 2
 15.30439|ISTEP 11. 3
 15.46324|ISTEP 11. 4
 15.57156|ISTEP 11. 5
 15.72994|ISTEP 11. 6
 16.86201|ISTEP 11. 7
 16.86278|ISTEP 11. 8
 17.21426|ISTEP 11. 9
 17.21514|ISTEP 11.10
 17.27511|ISTEP 11.11
 17.27597|ISTEP 11.12
 17.28864|ISTEP 11.13
 17.28950|ISTEP 12. 1
 17.38257|ISTEP 12. 2
 17.48634|ISTEP 12. 3
 17.51587|ISTEP 12. 4
 17.88007|ISTEP 12. 5
 17.88078|ISTEP 13. 1
 17.96599|ISTEP 13. 2
 18.04153|ISTEP 13. 3
 18.04233|ISTEP 13. 4
 18.08020|ISTEP 13. 5
 18.08752|ISTEP 13. 6
 18.97634|ISTEP 13. 7
 19.14892|ISTEP 13. 8
 19.30176|ISTEP 13. 9
 21.45463|ISTEP 13.10
 21.49420|ISTEP 13.11
 21.59584|ISTEP 13.12
 21.59661|ISTEP 14. 1
 21.62698|ISTEP 14. 2
 21.65510|ISTEP 14. 3
 24.69895|ISTEP 14. 4
 24.72871|ISTEP 14. 5
 24.77799|ISTEP 14. 6
 24.78823|ISTEP 14. 7
 24.89193|ISTEP 14. 8
 24.89385|ISTEP 15. 1
 25.75658|ISTEP 15. 2
 25.77616|ISTEP 15. 3
 25.90881|ISTEP 16. 1
 27.09374|ISTEP 16. 2
 27.42198|ISTEP 16. 3
 27.47594|ISTEP 16. 4
 27.48988|ISTEP 18.13
 27.62116|ISTEP 18.14
 27.62795|ISTEP 20. 1
 28.35592|ISTEP 21. 1
 34.46382|htmgt|User power limit has been set to 990W
 35.06428|htmgt|OCCs are now running in ACTIVE state
 43.07427|ISTEP 21. 2
 43.05869|ISTEP 21. 3
[   43.241813118,5] SkiBoot 4df5312 starting...
[   43.241816274,5] initial console log level: memory 7, driver 5
[   43.241819043,6] CPU: P8 generation processor(max 8 threads/core)
[   43.241821517,7] CPU: Boot CPU PIR is 0x0028 PVR is 0x004d0200
[   43.241824499,7] CPU: Initial max PIR set to 0x1fff
[   43.242283546,5] OPAL table: 0x300dae40 .. 0x300db300, branch table: 0x30002000
[   43.242288264,5] Assigning physical memory map table for unused
[   43.242291792,5] FDT: Parsing fdt @0xff00000
[   43.246166105,6] CHIP: Initialised chip 0 from xscom@3fc0000000000
[   43.246246940,5] XSCOM: chip 0x0 at 0x3fc0000000000 [P8 DD2.0]
[   43.246255595,6] XSTOP: XSCOM addr = 0x2010c82, FIR bit = 31
[   43.246258870,6] MFSI 0:0: Initialized
[   43.246261066,6] MFSI 0:2: Initialized
[   43.246263151,6] MFSI 0:1: Initialized
[   43.246584477,5] LPC: LPC[000]: Initialized, access via XSCOM @0xb0020
[   43.246591645,5] LPC: LPC: Default bus on chip 0x0
[   43.246693060,6] MEM: parsing reserved memory from node /ibm,hostboot/reserved-memory
[   43.246706980,7] HOMER: Init chip 0
[   43.246709625,7]   PBA BAR0 : 0x0000001ffd800000
[   43.246712290,7]   PBA MASK0: 0x0000000000300000
[   43.246714916,7]   HOMER Image at 0x1ffd800000 size 4MB
[   43.246718324,7]   PBA BAR2 : 0x4000001ffda00000
[   43.246720940,7]   PBA MASK2: 0x0000000000000000
[   43.246723333,7]   SLW Image at 0x1ffda00000 size 1MB
[   43.246726841,7]   PBA BAR3 : 0x0000001fff800000
[   43.246729316,7]   PBA MASK3: 0x0000000000700000
[   43.246731841,7]   OCC Common Area at 0x1fff800000 size 8MB
[   43.246755197,7] CPU idle state device tree init
[   43.246758453,5] SLW: HB-provided idle states property found
[   43.246762230,5] SLW: Enabling: nap
[   43.246764312,5] SLW: Enabling: fastsleep_
[   43.246766918,5] SLW: Enabling: winkle
[   43.246963225,5] PLAT: Fixing up PSI BAR on chip 0 BAR=3fffe80000001
[   43.246994331,7] AST: PNOR LPC offset: 0x0c000000
[   43.247065882,5] PLAT: Using virtual UART
[   43.247365494,7] UART: Using LPC IRQ 4
[   45.199391647,5] PLAT: Detected Habanero platform
[   45.250426673,5] PLAT: Detected BMC platform AMI
[   45.251450587,5] CENTAUR: Found centaur for chip 0x0 channel 0
[   45.294484723,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 3
[   45.333915468,5] CENTAUR: Found centaur for chip 0x0 channel 1
[   45.372473175,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 2
[   45.421473638,5] CENTAUR: Found centaur for chip 0x0 channel 4
[   45.435186919,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 7
[   45.488248367,5] CENTAUR: Found centaur for chip 0x0 channel 5
[   45.504047174,5] CENTAUR:   FSI host: 0x0 cMFSI0 port 6
[   46.028378327,5] PSI[0x000]: Found PSI bridge [active=0]
[   46.070273336,5] CPU: All 80 processors called in...
[    2.216710824,4] FLASH: No ffs info; using raw device only
[    2.216832586,5] BT: Interface initialized, IO 0x00e4
[    3.268216412,3] NVRAM: Common partition not found !
[    3.268281955,3] NVRAM: Look up for 'log-level-driver' failed due to bad format!
[    3.310186477,3] NVRAM: Common partition not found !
[    3.310243119,3] NVRAM: Look up for 'log-level-memory' failed due to bad format!
[    3.368039329,3] NVRAM: Common partition not found !
[    3.398417109,3] NVRAM: Look up for 'force-secure-mode' failed due to bad format!
[    3.429923087,5] STB: secure mode off
[    3.429965701,3] NVRAM: Common partition not found !
[    3.460098056,3] NVRAM: Look up for 'force-trusted-mode' failed due to bad format!
[    4.004516606,5] STB: trusted mode off
[    4.004564798,5] OPAL: Using OPAL UART console
[    4.042646313,3] NVRAM: Common partition not found !
[    4.065958609,3] NVRAM: Look up for 'uart-con-policy' failed due to bad format!
[    4.091212536,3] NVRAM: Common partition not found !
[    4.128928407,3] NVRAM: Look up for 'pcie-max-link-speed' failed due to bad format!
[    4.173080111,5] FLASH: Queueing preload of 2/200ea
[    4.203754428,5] FLASH: Queueing preload of 0/0
[    4.203754809,4] FLASH: Can't load resource id:2. No system flash found
[    4.281025848,5] FLASH: Queueing preload of 1/0
[    4.281026091,4] FLASH: Can't load resource id:0. No system flash found
[    4.357331359,4] FLASH: Can't load resource id:1. No system flash found
[    4.357369885,6] NX0: RNG BAR set to 0x0003ffff40000000..0x0003ffff40000fff
[    4.357374460,6] NX0: Crypto at 0x2010000
[    4.357378031,7] NX0:   DMA 0x00000188eb80002c
[    4.357380571,6] NX0:   SYM CT already set to 1
[    4.357381533,6] NX0:   SYM CI already set to 1
[    4.357382825,7] NX0:   SYM Config 0x8008010000000000
[    4.357386031,6] NX0:   ASYM CT already set to 2
[    4.357386991,6] NX0:   ASYM CI already set to 1
[    4.357388911,7] NX0:   ASYM Config 0x8020020000000000
[    4.357390609,7] NX0:   CRB Input Queue 0x0000000000000000
[    4.357392229,7] NX0:   Engine Enable 0x8000000000000003
[    4.357393496,6] NX0: Crypto Coprocessors Disabled (not supported)
[    4.357394976,6] NX0: 842 at 0x2010000
[    4.357397364,7] NX0:   DMA 0x00000188ff8000af
[    4.357398687,6] NX0:   842 CT set to 3
[    4.357399530,6] NX0:   842 CI already set to 1
[    4.357401196,7] NX0:   842 Config 0x00080300f8000001
[    4.357403403,7] NX0:   Engine Enable 0x8000000000000003
[    4.357404610,6] NX0: 842 Coprocessor Enabled
[    4.357484463,5] Chip 0 Found PBCQ0 at /xscom@3fc0000000000/pbcq@2012000
[    4.357487542,7] PHB3[0:0]: X[PE]=0x02012000 X[PCI]=0x09012000 X[SPCI]=0x09013c00
[    4.357490812,7] PHB3[0:0] REGS     = 0x0003fffe40000000 [4k]
[    4.357493070,7] PHB3[0:0] PCIBAR   = 0x0003fffe40000000
[    4.357495388,7] PHB3[0:0] MMIO0    = 0x0000200000000000 [0x0000010000000000]
[    4.357498607,7] PHB3[0:0] MMIO1    = 0x00003fe000000000 [0x0000000080000000]
[    4.357500534,7] PHB3[0:0] BAREN    = 0xf800000000000000
[    4.357504323,7] PHB3[0:0] NEWBAREN = 0xf800000000000000
[    4.357506463,7] PHB3[0:0] IRSNC    = 0x0100000000000000
[    4.357508427,7] PHB3[0:0] IRSNM    = 0xff00000000000000
[    4.357509714,7] PHB3[0:0] LSI      = 0xff00000000000000
[    4.357516725,5] Chip 0 Found PBCQ1 at /xscom@3fc0000000000/pbcq@2012400
[    4.357519737,7] PHB3[0:1]: X[PE]=0x02012400 X[PCI]=0x09012400 X[SPCI]=0x09013c40
[    4.357522642,7] PHB3[0:1] REGS     = 0x0003fffe40100000 [4k]
[    4.357524878,7] PHB3[0:1] PCIBAR   = 0x0003fffe40100000
[    4.357527012,7] PHB3[0:1] MMIO0    = 0x0000210000000000 [0x0000010000000000]
[    4.357530548,7] PHB3[0:1] MMIO1    = 0x00003fe080000000 [0x0000000080000000]
[    4.357532396,7] PHB3[0:1] BAREN    = 0xf800000000000000
[    4.357535170,7] PHB3[0:1] NEWBAREN = 0xf800000000000000
[    4.357537076,7] PHB3[0:1] IRSNC    = 0x0200000000000000
[    4.357538895,7] PHB3[0:1] IRSNM    = 0xff00000000000000
[    4.357540143,7] PHB3[0:1] LSI      = 0xff00000000000000
[    4.357546973,5] Chip 0 Found PBCQ2 at /xscom@3fc0000000000/pbcq@2012800
[    4.357549998,7] PHB3[0:2]: X[PE]=0x02012800 X[PCI]=0x09012800 X[SPCI]=0x09013c80
[    4.357552445,7] PHB3[0:2] REGS     = 0x0003fffe40200000 [4k]
[    4.357555130,7] PHB3[0:2] PCIBAR   = 0x0003fffe40200000
[    4.357558010,7] PHB3[0:2] MMIO0    = 0x0000220000000000 [0x0000010000000000]
[    4.357560386,7] PHB3[0:2] MMIO1    = 0x00003fe100000000 [0x0000000080000000]
[    4.357563713,7] PHB3[0:2] BAREN    = 0xf800000000000000
[    4.357566474,7] PHB3[0:2] NEWBAREN = 0xf800000000000000
[    4.357568388,7] PHB3[0:2] IRSNC    = 0x0300000000000000
[    4.357570207,7] PHB3[0:2] IRSNM    = 0xff00000000000000
[    4.357571448,7] PHB3[0:2] LSI      = 0xff00000000000000
[    4.357621648,7] PHB#0000:00:00.0 PCI: Registered PHB
[    4.357623885,6] PHB#0000: Found /pciex@3fffe40000000 @[0:0]
[    4.357625625,6] PHB#0000:   M32 [0x00003fe000000000..0x00003fe07fffffff]
[    4.357627292,6] PHB#0000:   M64 [0x0000200000000000..0x000020ffffffffff]
[    4.357629151,3] PHB#0000: Base location code not found !
[    4.357630363,6] PHB#0000: Max link speed: GEN3
[    4.357631481,7] PHB#0000: Override lane equalization settings:
[    4.357632640,7] PHB#0000:   0x3333333333333333 0x3333333333333333
[    4.357634284,7] PHB#0000:   0x3333333333333333 0x3333333333333333
[    4.357839376,7] IRQ: Registering 0800..0ff7 ops @0x300a9f20 (data 0x3044a2f0)
[    4.357841718,7] IRQ: Registering 0ff8..0fff ops @0x300a9f50 (data 0x3044a2f0)
[    4.357843554,7] PHB#0000: Initializing PHB...
[    4.393687135,7] BT: seq 0x04 netfn 0x0a cmd 0x48: IPMI MSG done
[    4.393725395,7] BT: seq 0x05 netfn 0x06 cmd 0x06: Message sent to host
[    9.053197688,7] PHB#0000: Core revision 0xa30005
[    9.053203841,7] PHB#0000: Default system config: 0x441100fc30000000
[    9.053205407,7] PHB#0000: New system config    : 0x441000fc30000000
[    9.053207087,7] PHB#0000: PHB_RESET is 0x0000000000000000
[    9.053436572,7] PHB#0000: Waiting for DLP PG reset to complete...
[    9.061747789,7] PHB#0000: Initialization complete
[    9.061749151,3] CAPP: Error loading ucode lid. index=200ea
[    9.061758063,7] PHB#0001:00:00.0 PCI: Registered PHB
[    9.061760180,6] PHB#0001: Found /pciex@3fffe40100000 @[0:1]
[    9.061761819,6] PHB#0001:   M32 [0x00003fe080000000..0x00003fe0ffffffff]
[    9.061763448,6] PHB#0001:   M64 [0x0000210000000000..0x000021ffffffffff]
[    9.061765249,3] PHB#0001: Base location code not found !
[    9.061766405,6] PHB#0001: Max link speed: GEN3
[    9.061767518,7] PHB#0001: Override lane equalization settings:
[    9.061768636,7] PHB#0001:   0x3333333333333333 0x3333333333333333
[    9.061770211,7] PHB#0001:   0x3333333333333333 0x3333333333333333
[    9.061991002,7] IRQ: Registering 1000..17f7 ops @0x300a9f20 (data 0x30474418)
[    9.061993231,7] IRQ: Registering 17f8..17ff ops @0x300a9f50 (data 0x30474418)
[    9.061994933,7] PHB#0001: Initializing PHB...
[    9.076231263,7] BT: seq 0x05 netfn 0x06 cmd 0x06: IPMI MSG done
[   10.250947978,7] BT: seq 0x06 netfn 0x06 cmd 0x2e: Message sent to host
[   10.333343846,3] PHB#0002: Base location code not found !
[   10.412478146,3] NVRAM: Common partition not found !
[   10.412535067,3] NVRAM: Look up for 'nv_zcal_override' failed due to bad format!
[   10.434646901,5] PCI: Resetting PHBs...
[   12.082050967,5] PCI: Probing slots...
[   12.138441345,5] PHB#0000:00:00.0 [ROOT] 1014 03dc R:00 C:060400 B:01..01 SLOT=Slot3 
[   12.138598653,5] PHB#0000:01:00.0 [EP  ] 14e4 168a R:10 C:020000 (      ethernet) LOC_CODE=Slot3
[   12.167126660,5] PHB#0000:01:00.1 [EP  ] 14e4 168a R:10 C:020000 (      ethernet) LOC_CODE=Slot3
[   12.214285214,5] PHB#0000:01:00.2 [EP  ] 14e4 168a R:10 C:020000 (      ethernet) LOC_CODE=Slot3
[   12.249787681,5] PHB#0000:01:00.3 [EP  ] 14e4 168a R:10 C:020000 (      ethernet) LOC_CODE=Slot3
[   12.321892635,5] PHB#0001:00:00.0 [ROOT] 1014 03dc R:00 C:060400 B:01..15 SLOT=Backplane PLX 
[   12.327076274,5] PHB#0001:01:00.0 [SWUP] 10b5 8748 R:ca C:060400 B:02..15 LOC_CODE=Backplane PLX
[   12.388024639,5] PHB#0001:02:01.0 [SWDN] 10b5 8748 R:ca C:060400 B:03..07 SLOT=S000103 
[   12.414459116,5] PHB#0001:02:08.0 [SWDN] 10b5 8748 R:ca C:060400 B:08..08 
[   12.470414543,5] PHB#0001:08:00.0 [LGCY] 1b4b 9235 R:11 C:010601 (          sata) LOC_CODE=Backplane PLX
[   13.014418490,5] PHB#0001:02:09.0 [SWDN] 10b5 8748 R:ca C:060400 B:09..09 SLOT=S000109 
[   13.056007887,5] PHB#0001:09:00.0 [EP  ] 104c 8241 R:02 C:0c0330 (      usb-xhci) LOC_CODE=S000109
[   13.112263151,5] PHB#0001:02:0a.0 [SWDN] 10b5 8748 R:ca C:060400 B:0a..0b 
[   13.134965615,5] PHB#0001:0a:00.0 [ETOX] 1a03 1150 R:03 C:060400 B:0b..0b LOC_CODE=Backplane PLX
[   13.210830602,5] PHB#0001:0b:00.0 [PCID] 1a03 2000 R:30 C:030000 (           vga) LOC_CODE=Backplane PLX
[   13.219453631,5] PHB#0001:02:10.0 [SWDN] 10b5 8748 R:ca C:060400 B:0c..10 
[   13.270814159,5] PHB#0001:02:11.0 [SWDN] 10b5 8748 R:ca C:060400 B:11..15 
[   13.295985096,5] PHB#0002:00:00.0 [ROOT] 1014 03dc R:00 C:060400 B:01..ff SLOT=Slot4 
[   13.322428511,5] irq 10 name: psi:fsp (7/0)
[   13.382938579,5] irq 11 name: psi:occ (7/8)
[   13.403387135,5] irq 12 name: psi:fsi (7/16)
[   13.403435799,5] irq 13 name: psi:lpchc (9/24)
[   13.419227991,5] irq 14 name: psi:local_err (13/34)
[   13.434107736,5] irq 15 name: psi:external (12/48)
[   13.473658756,5] irq ffe name: <null> (0/61)
[   13.493578580,5] irq fff name: <null> (0/62)
[   14.019948470,5] irq 17fe name: <null> (0/63)
[   14.020001180,5] irq 17ff name: <null> (0/64)
[   14.086461128,5] irq 1ffe name: <null> (0/65)
[   14.143394131,5] irq 1fff name: <null> (0/66)
[   14.143512015,5] IPMI: Resetting boot count on successful boot
[   14.173649174,5] INIT: Waiting for kernel...
[   14.188933247,5] INIT: platform wait for kernel load failed
[   14.209182025,5] INIT: Assuming kernel at 0x20000000
[   14.273331060,5] INIT: Kernel loaded, size: 4096 bytes (0 = unknown preload)
[   14.282753665,5] INIT: ELF header not found. Assuming raw binary.
[   14.301612737,5] OCC: All Chip Rdy after 0 ms
[   14.316713423,3] NVRAM: Common partition not found !
[   14.324084839,3] NVRAM: Look up for 'bootargs' failed due to bad format!
[   14.352938186,5] INIT: stdout-path: /ibm,opal/consoles/serial@0
[   14.372740182,5] INIT: Starting kernel at 0x0, fdt at 0x304d5ff8 87340 bytes)
[   14.409358671,3] ***********************************************
[   14.434065777,3] Unexpected exception e40 !
[   14.434135457,3] SRR0 : 00000000300027b4 SRR1 : 90000000001a1000
[   14.448491960,3] HSRR0: 0000000000000000 HSRR1: 9000000000001000
[   14.503336559,3] LR   : 00000000300144c4 CTR  : 0000000000000000
[   15.044944444,3] CFAR : 000000003000519c
[   15.045009439,3] CR   : 40002082  XER: 20000000
[   15.081427647,3] GPR00: 0000000030014478 GPR16: 0000000000000000
[   15.101987960,3] GPR01: 0000000031ca3b80 GPR17: 0000000000000000
[   15.127327593,3] GPR02: 00000000300e2e00 GPR18: 0000000000000000
[   15.153063230,3] GPR03: 00000000304d5ff8 GPR19: 0000000000000000
[   15.186152534,3] GPR04: 0000000000000000 GPR20: 0000000000000000
[   15.209979147,3] GPR05: 0000000000000000 GPR21: 0000000000000000
[   15.235350051,3] GPR06: 0000000065504150 GPR22: 0000000000000000
[   15.270375813,3] GPR07: 0000000040000001 GPR23: 00000000300a313b
[   15.296201492,3] GPR08: 0000000030000000 GPR24: 000000003021c708
[   15.311647943,3] GPR09: 00000000300050b0 GPR25: 0000000000000000
[   15.335565719,3] GPR10: 00000000000050b0 GPR26: 0000000040000000
[   15.344233407,3] GPR11: 0000000000000000 GPR27: 0000000000000001
[   15.373267092,3] GPR12: 0000000040002084 GPR28: 0000000000000000
[   15.413860369,3] GPR13: 0000000031ca0000 GPR29: 0000000000000000
[   15.423612647,3] GPR14: 0000000030002604 GPR30: 000000003021c6e0
[   15.460392285,3] GPR15: 0000000000000000 GPR31: 000000003021c6d0
[   15.481166674,0] Aborting!
CPU 0028 Backtrace:
 S: 0000000031ca39f0 R: 00000000300136a8   .backtrace+0x24
 S: 0000000031ca3a70 R: 00000000300194f0   ._abort+0x4c
 S: 0000000031ca3af0 R: 0000000030026a8c   .exception_entry+0x114
 S: 0000000031ca3b80 R: 0000000000001f00 * +0x1f00
 S: 0000000031ca3d50 R: 0000000030014478   .load_and_boot_kernel+0xa0c
 S: 0000000031ca3e30 R: 0000000030014bc4   .main_cpu_entry+0x63c
 S: 0000000031ca3f00 R: 0000000030002648   boot_entry+0x198

**Comment by pridhiviraj** [comment]
Pflash Version:
root@ltc-test-hab02:~/skiboot/external/pflash# pflash  --version
Open-Power Flash tool pflash-5.6.0-123-g4df5312
root@ltc-test-hab02:~/skiboot/external/pflash# pflash -p skiboot.lid.xz -e -P PAYLOAD
WARNING: Erase region adjusted to 0x00ca9000..0x00cf5000
About to erase 0x00ca9000..0x00cf5000 !
WARNroot@ltc-test-hab02:~/skiboot/external/pflash# pflash  --version
Open-Power Flash tool pflash-5.6.0-123-g4df5312
root@ltc-test-hab02:~/skiboot/external/pflash# pflash -p skiboot.lid.xz -e -P PAYLOAD
WARNING: Erase region adjusted to 0x00ca9000..0x00cf5000
About to erase 0x00ca9000..0x00cf5000 !
WARNING ! This will modify your HOST flash chip content !
Enter "yes" to confirm:yes
Erasing...
About to program "skiboot.lid.xz" at 0x00ca9000..0x00cf4b80 !
Programming & Verifying...
[==================================================] 100%
Updating actual size in partition header...
ING ! This will modify your HOST flash chip content !
Enter "yes" to confirm:yes
Erasing...
About to program "skiboot.lid.xz" at 0x00ca9000..0x00cf4b80 !
Programming & Verifying...
[==================================================] 100%
Updating actual size in partition header...

**Comment by pridhiviraj** [comment]
As system is down, i try to get the info of PNOR partition using some stable pflash on BMC busy box.
# ./pflash --info
Flash info:
-----------
Name          = Macronix MXxxL51235F
Total size    = 64MB 
Erase granule = 4KB 

Partitions:
-----------
ID=00            part 00000000..00001000 (actual=00001000)
ID=01            HBEL 00008000..0002c000 (actual=00024000)
ID=02           GUARD 0002c000..00031000 (actual=00005000)
ID=03             HBD 00031000..00091000 (actual=00060000)
ID=04           DJVPD 00091000..000d9000 (actual=00048000)
ID=05            MVPD 000d9000..00169000 (actual=00090000)
ID=06            CVPD 00169000..001b1000 (actual=00048000)
ID=07             HBI 001b1000..00751000 (actual=005a0000)
ID=08            SBEC 00751000..007e1000 (actual=00090000)
ID=09             SBE 007e1000..00829000 (actual=00048000)
ID=10            WINK 00829000..00949000 (actual=00120000)
ID=11            HBRT 00949000..00ca9000 (actual=00360000)
FFS: Bad entry 12 in partition map
Error 102 scanning partitions
# 
# ./pflash -v    
Palmetto Flash tool 0.8.5
# 


By this tool in busybox, i am able to flash all the lids/ pnor images earlier without any issues. Looks like some thing got corrupted in PNOR. Which leads to fail the boot.

**Comment by pridhiviraj** [comment]
I reverted pflash version to one commit lower, it flashes and boots fine.
Looks like this is the commit causing the issues https://github.com/open-power/skiboot/commit/73e1e8a727a9e7179719eb7844bd4248d9890114

**Comment by pridhiviraj** [comment]
pflash  --version
Open-Power Flash tool pflash-5.6.0-119-g396b940

Nope, some thing went wrong with this level also. When i look at the booting side it boots from golden side instead of primary side.
# ipmitool -I lanplus -H <BMC-IP>  -U ADMIN -P admin sensor list | grep -i golden
BIOS Golden Side | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na        
BMC Golden Side  | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
#

**Comment by cyrilbur-ibm** [comment]
Hi Pridiviraj,

Was this running pflash always on the BMC or were some commands run from the host?

**Comment by pridhiviraj** [comment]
The failed case is where i tried flashing skiboot using upstream pflash in host.
To recover back used some stable pflash in BMC in the passed case.

**Comment by cyrilbur-ibm** [comment]
So I have a fix. I don't understand how it fixes it. I'll do some more testing Monday.

**Comment by pridhiviraj** [comment]
@cyrilbur-ibm Cool. Thanks.

**Comment by cyrilbur-ibm** [comment]
The reason memset() the struct to zero works is that we memset the checksum word.
I've posted the fix to skiboot list: http://patchwork.ozlabs.org/patch/780576/
