### ISSUE TITLE
PCI Hotplug Support

### ISSUE THREAD

**Issue by causten** [open-power/skiboot#9]
Does Skiboot/Opal support hotplug of PCIe cards?

**Comment by ozbenh** [comment]
On Wed, 2015-02-25 at 06:29 -0800, Chris Austen wrote:
> Does Skiboot/Opal support hotplug of PCIe cards?

It's a work in progress. We have a code we are still reviewing & testing
to support hotplug on Tuleta. If the context is a different machine then
some code will have to be written to deal with the specific HW hotplug
controller used on it.

Cheers,
Ben.
