### ISSUE TITLE
POWER9 HDAT unit tests

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/skiboot#95]
`hdata/test/` contains unit tests where we pass in HDAT dumps to `hdata_to_dt` so we can diff the resultant device tree.

We need to add P9 Dumps in, now that HDAT seems to have somewhat stabilized.

We'll need from romulus, boston, witherspoon, zz.

**Comment by oohal** [comment]
We've got an OP920 dump from witherspoon in there now.
